"""Vauban - MLX-native abliteration toolkit for Apple Silicon."""

from pathlib import Path

from vauban._pipeline import run
from vauban._version import __version__
from vauban.api_eval import evaluate_suffix_via_api
from vauban.api_eval_proxy import evaluate_with_defense_proxy
from vauban.cast import cast_generate, cast_generate_svf
from vauban.circuit import trace_circuit
from vauban.config import generate_config_schema, load_config, write_config_schema
from vauban.config._validation import validate_config
from vauban.cut import (
    cut,
    cut_biprojected,
    cut_false_refusal_ortho,
    cut_subspace,
    save_weights,
    sparsify_direction,
    target_weight_keys,
)
from vauban.dataset import load_hf_prompts, resolve_prompts
from vauban.defend import defend_content, defend_tool_call
from vauban.depth import depth_direction, depth_generate, depth_profile
from vauban.dequantize import dequantize_model, is_quantized
from vauban.detect import detect
from vauban.environment import (
    compute_reward,
    run_agent_loop,
    score_candidates_via_rollout,
)
from vauban.evaluate import evaluate
from vauban.export import export_model
from vauban.features import train_sae, train_sae_multi_layer
from vauban.fusion import fuse_and_generate, fuse_batch
from vauban.geometry import (
    DirectionGeometryResult,
    DirectionPair,
    analyze_directions,
)
from vauban.intent import capture_intent, check_alignment
from vauban.linear_probe import train_probe
from vauban.measure import (
    default_eval_path,
    default_prompt_paths,
    detect_layer_types,
    find_instruction_boundary,
    load_prompts,
    measure,
    measure_dbdi,
    measure_diff,
    measure_subspace,
    measure_subspace_bank,
    select_target_layers,
    silhouette_scores,
)
from vauban.optimize import optimize, optimize_composition
from vauban.policy import evaluate_data_flow, evaluate_tool_call
from vauban.probe import multi_probe, probe, steer, steer_svf
from vauban.repbend import repbend
from vauban.scan import calibrate_scan_threshold
from vauban.scan import scan as injection_scan
from vauban.sic import calibrate_threshold, sic_single
from vauban.sic import sic as sic_sanitize
from vauban.softprompt import softprompt_attack
from vauban.subspace import (
    effective_rank,
    explained_variance_ratio,
    grassmann_distance,
    orthonormalize,
    principal_angles,
    project_subspace,
    remove_subspace,
    subspace_overlap,
)
from vauban.surface import (
    aggregate,
    compare_surfaces,
    default_multilingual_surface_path,
    default_surface_path,
    find_threshold,
    load_surface_prompts,
    map_surface,
    scan,
)
from vauban.svf import (
    load_svf_boundary,
    save_svf_boundary,
    svf_gradient,
    train_svf_boundary,
)
from vauban.types import (
    AgentTurn,
    AlphaTier,
    ApiEvalEndpoint,
    CastConfig,
    CastResult,
    CausalLM,
    CircuitConfig,
    CircuitResult,
    ComponentEffect,
    ComposeOptimizeConfig,
    ComposeOptimizeResult,
    CompositionTrialResult,
    CutConfig,
    DataFlowRule,
    DatasetRef,
    DBDIResult,
    DefenseProxyResult,
    DefenseStackConfig,
    DefenseStackResult,
    DepthConfig,
    DepthDirectionResult,
    DepthResult,
    DetectConfig,
    DetectResult,
    DiffResult,
    DirectionResult,
    DirectionTransferResult,
    EnvironmentConfig,
    EnvironmentResult,
    EvalConfig,
    EvalResult,
    FeaturesConfig,
    FeaturesResult,
    FusionConfig,
    FusionGeneration,
    FusionResult,
    IntentCheckResult,
    IntentConfig,
    IntentState,
    LinearProbeConfig,
    LinearProbeLayerResult,
    LinearProbeResult,
    MeasureConfig,
    MetaConfig,
    OptimizeConfig,
    OptimizeResult,
    PipelineConfig,
    PolicyConfig,
    PolicyDecision,
    PolicyRule,
    ProbeConfig,
    ProbeResult,
    RateLimitRule,
    RepBendConfig,
    RepBendResult,
    SAELayerResult,
    ScanConfig,
    ScanResult,
    ScanSpan,
    SICConfig,
    SICPromptResult,
    SICResult,
    SoftPromptConfig,
    SoftPromptResult,
    SteerConfig,
    SteerResult,
    SubspaceResult,
    SurfaceComparison,
    SurfaceConfig,
    SurfaceGroup,
    SurfaceGroupDelta,
    SurfacePoint,
    SurfacePrompt,
    SurfaceResult,
    SVFConfig,
    SVFResult,
    TokenDepth,
    Tokenizer,
    ToolCall,
    ToolSchema,
    TransferEvalResult,
    TrialResult,
)

__all__ = [
    "AgentTurn",
    "AlphaTier",
    "ApiEvalEndpoint",
    "CastConfig",
    "CastResult",
    "CausalLM",
    "CircuitConfig",
    "CircuitResult",
    "ComponentEffect",
    "ComposeOptimizeConfig",
    "ComposeOptimizeResult",
    "CompositionTrialResult",
    "CutConfig",
    "DBDIResult",
    "DataFlowRule",
    "DatasetRef",
    "DefenseProxyResult",
    "DefenseStackConfig",
    "DefenseStackResult",
    "DepthConfig",
    "DepthDirectionResult",
    "DepthResult",
    "DetectConfig",
    "DetectResult",
    "DiffResult",
    "DirectionGeometryResult",
    "DirectionPair",
    "DirectionResult",
    "DirectionTransferResult",
    "EnvironmentConfig",
    "EnvironmentResult",
    "EvalConfig",
    "EvalResult",
    "FeaturesConfig",
    "FeaturesResult",
    "FusionConfig",
    "FusionGeneration",
    "FusionResult",
    "IntentCheckResult",
    "IntentConfig",
    "IntentState",
    "LinearProbeConfig",
    "LinearProbeLayerResult",
    "LinearProbeResult",
    "MeasureConfig",
    "MetaConfig",
    "OptimizeConfig",
    "OptimizeResult",
    "PipelineConfig",
    "PolicyConfig",
    "PolicyDecision",
    "PolicyRule",
    "ProbeConfig",
    "ProbeResult",
    "RateLimitRule",
    "RepBendConfig",
    "RepBendResult",
    "SAELayerResult",
    "SICConfig",
    "SICPromptResult",
    "SICResult",
    "SVFConfig",
    "SVFResult",
    "ScanConfig",
    "ScanResult",
    "ScanSpan",
    "SoftPromptConfig",
    "SoftPromptResult",
    "SteerConfig",
    "SteerResult",
    "SubspaceResult",
    "SurfaceComparison",
    "SurfaceConfig",
    "SurfaceGroup",
    "SurfaceGroupDelta",
    "SurfacePoint",
    "SurfacePrompt",
    "SurfaceResult",
    "TokenDepth",
    "Tokenizer",
    "ToolCall",
    "ToolSchema",
    "TransferEvalResult",
    "TrialResult",
    "__version__",
    "aggregate",
    "analyze_directions",
    "calibrate_scan_threshold",
    "calibrate_threshold",
    "capture_intent",
    "cast_generate",
    "cast_generate_svf",
    "check_alignment",
    "compare_surfaces",
    "compute_reward",
    "cut",
    "cut_biprojected",
    "cut_false_refusal_ortho",
    "cut_subspace",
    "default_eval_path",
    "default_multilingual_surface_path",
    "default_prompt_paths",
    "default_surface_path",
    "defend_content",
    "defend_tool_call",
    "depth_direction",
    "depth_generate",
    "depth_profile",
    "dequantize_model",
    "detect",
    "detect_layer_types",
    "effective_rank",
    "evaluate",
    "evaluate_data_flow",
    "evaluate_suffix_via_api",
    "evaluate_tool_call",
    "evaluate_with_defense_proxy",
    "explained_variance_ratio",
    "export_model",
    "find_instruction_boundary",
    "find_threshold",
    "fuse_and_generate",
    "fuse_batch",
    "generate_config_schema",
    "grassmann_distance",
    "injection_scan",
    "is_quantized",
    "load_config",
    "load_hf_prompts",
    "load_prompts",
    "load_surface_prompts",
    "load_svf_boundary",
    "map_surface",
    "measure",
    "measure_dbdi",
    "measure_diff",
    "measure_subspace",
    "measure_subspace_bank",
    "multi_probe",
    "optimize",
    "optimize_composition",
    "orthonormalize",
    "principal_angles",
    "probe",
    "project_subspace",
    "remove_subspace",
    "repbend",
    "resolve_prompts",
    "run",
    "run_agent_loop",
    "save_svf_boundary",
    "save_weights",
    "scan",
    "score_candidates_via_rollout",
    "select_target_layers",
    "sic_sanitize",
    "sic_single",
    "silhouette_scores",
    "softprompt_attack",
    "sparsify_direction",
    "steer",
    "steer_svf",
    "subspace_overlap",
    "svf_gradient",
    "target_weight_keys",
    "trace_circuit",
    "train_probe",
    "train_sae",
    "train_sae_multi_layer",
    "train_svf_boundary",
    "validate",
    "write_config_schema",
]


def validate(config_path: str | Path) -> list[str]:
    """Validate a TOML config without loading any model."""
    return validate_config(config_path)
