# SPDX-FileCopyrightText: 2026 Teilo Millet
# SPDX-License-Identifier: Apache-2.0

"""Behavior-change report primitives for model behavior auditing."""

from vauban.behavior._markdown import render_behavior_report_markdown
from vauban.behavior._primitives import (
    AccessLevel,
    AccessPolicy,
    ActivationFinding,
    BehaviorChatMessage,
    BehaviorClaim,
    BehaviorDiffResult,
    BehaviorExample,
    BehaviorMetric,
    BehaviorMetricDelta,
    BehaviorMetricSpec,
    BehaviorObservation,
    BehaviorPrompt,
    BehaviorReport,
    BehaviorSuite,
    BehaviorSuiteRef,
    BehaviorTrace,
    ChatRole,
    ClaimStatus,
    ClaimStrength,
    EvidenceKind,
    EvidenceRef,
    ExampleRedaction,
    ExpectedBehavior,
    FindingSeverity,
    InterventionEffect,
    InterventionKind,
    InterventionPolarity,
    InterventionResult,
    JsonScalar,
    JsonValue,
    MetricPolarity,
    MetricQuality,
    ModelRole,
    ReportModelRef,
    ReproducibilityInfo,
    ReproductionResult,
    ReproductionTarget,
    TransformationKind,
    TransformationRef,
    compare_behavior_metrics,
)
from vauban.behavior._trace import (
    aggregate_trace_metrics,
    build_behavior_diff_result,
    infer_behavior_metric_specs,
    load_behavior_trace,
    write_behavior_trace,
)

__all__ = [
    "AccessLevel",
    "AccessPolicy",
    "ActivationFinding",
    "BehaviorChatMessage",
    "BehaviorClaim",
    "BehaviorDiffResult",
    "BehaviorExample",
    "BehaviorMetric",
    "BehaviorMetricDelta",
    "BehaviorMetricSpec",
    "BehaviorObservation",
    "BehaviorPrompt",
    "BehaviorReport",
    "BehaviorSuite",
    "BehaviorSuiteRef",
    "BehaviorTrace",
    "ChatRole",
    "ClaimStatus",
    "ClaimStrength",
    "EvidenceKind",
    "EvidenceRef",
    "ExampleRedaction",
    "ExpectedBehavior",
    "FindingSeverity",
    "InterventionEffect",
    "InterventionKind",
    "InterventionPolarity",
    "InterventionResult",
    "JsonScalar",
    "JsonValue",
    "MetricPolarity",
    "MetricQuality",
    "ModelRole",
    "ReportModelRef",
    "ReproducibilityInfo",
    "ReproductionResult",
    "ReproductionTarget",
    "TransformationKind",
    "TransformationRef",
    "aggregate_trace_metrics",
    "build_behavior_diff_result",
    "compare_behavior_metrics",
    "infer_behavior_metric_specs",
    "load_behavior_trace",
    "render_behavior_report_markdown",
    "write_behavior_trace",
]
